ovirt_repositories_subscription_manager_repos:
  - rhel-7-server-rpms
  - rhel-7-server-supplementary-rpms
  - rhel-7-server-rhv-4.1-rpms
  - rhel-7-server-rhv-4-tools-rpms
  - jb-eap-7-for-rhel-7-server-rpms
