---
- name: Find existing Storage Domains
  ovirt_storage_domain_info:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ data_center_name }}"
  register: sd_info

- name: Remove Storage Domains apart from master
  ovirt_storage_domain:
    state: absent
    id: "{{ ovirt_item.id }}"
    auth: "{{ ovirt_auth }}"
    format: "{{ format_storages }}"
  with_items: "{{ sd_info.ovirt_storage_domains }}"
  when: not ovirt_item.master
  loop_control:
    loop_var: ovirt_item

- name: Put in maintainance master Storage Domain
  ovirt_storage_domain:
    state: maintenance
    id: "{{ ovirt_item.id }}"
    data_center: "{{ data_center_name }}"
    auth: "{{ ovirt_auth }}"
  with_items: "{{ sd_info.ovirt_storage_domains }}"
  when: ovirt_item.master
  loop_control:
    loop_var: ovirt_item
