---
- name: Find existing VMPools
  ovirt_vmpool_info:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ data_center_name }}"
  register: vmpool_info

- name: Remove VMPools
  ovirt_vmpool:
    state: absent
    name: "{{ ovirt_item.name }}"
    auth: "{{ ovirt_auth }}"
  with_items: "{{ vmpool_info.ovirt_vm_pools }}"
  loop_control:
    loop_var: ovirt_item
