---
- name: Clean temporary resources
  block:
  - name: Fetch logs from the engine VM
    include_tasks: fetch_engine_logs.yml
    ignore_errors: true
  - include_tasks: clean_localvm_dir.yml
  - name: Clean local storage pools
    include_tasks: clean_local_storage_pools.yml
    ignore_errors: true
...
