---
- name: Validate IP prefix
  block:
    - name: IPv4 Validation
      block:
        - name: Get IPv4 route
          command: ip route get {{ he_ipv4_subnet_prefix + ".1" }}
          register: ip_route_result
        - debug: var=ip_route_result
        - name: Check if route exists
          include_tasks: search_available_network_subnet.yaml
          when: ip_route_result.stdout.find("via") == -1
      when: not ipv6_deployment|bool
    - name: IPv6 Validation
      block:
        - name: Get IPv6 route
          command: ip route get {{ he_ipv6_subnet_prefix + "::1" }}
          register: ip_route_result
        - debug: var=ip_route_result
        - name: Check if route exists
          include_tasks: search_available_network_subnet.yaml
          when: ip_route_result.stdout.find("via") == -1
      when: ipv6_deployment|bool
