---
- name: "Find repo files to backup"
  find:
    paths: "/etc/yum.repos.d"
    patterns: "*.repo"
  tags: backup
  register: files_to_backup

- name: Creating folder to backup repositories files
  file:
    path: "{{ ovirt_repositories_repos_backup_path }}"
    state: directory
    mode: 0755
  tags: backup
  when: files_to_backup.files

- name: Copy current repositories files to backup folder
  copy:
    src: "{{ item.path }}"
    dest: "{{ ovirt_repositories_repos_backup_path }}"
    remote_src: yes
    mode: preserve
  with_items: "{{ files_to_backup.files }}"
  tags:
    - skip_ansible_lint
    - backup
