---
- name: Ensure subscription-manager package is installed
  package:
    name: subscription-manager
    state: present

- name: Install Satellite certificates
  dnf:
    name: "{{ ovirt_repositories_ca_rpm_url }}"
    state: present
    validate_certs: "{{ ovirt_repositories_ca_rpm_validate_certs | default(omit) }}"
    disable_gpg_check: "{{ ovirt_repositories_ca_rpm_disable_gpg_check | default(omit) }}"
  when: ovirt_repositories_ca_rpm_url is defined

- name: Register to subscription manager
  command: |
    subscription-manager register
    --org {{ ovirt_repositories_org }}
    --activationkey {{ ovirt_repositories_activationkey }}
    {% if ovirt_repositories_force_register is defined and ovirt_repositories_force_register|bool %} --force {% endif %}
  changed_when: false

- name: Enable dnf modules
  command: "dnf module enable -y {{ ovirt_repositories_dnf_modules | join(' ') }}"
  args:
    warn: False
  when:
    - ovirt_repositories_ovirt_version|string >= '4.4'
    - ovirt_repositories_target_host == 'engine'

- name: set ovirt_repositories_subscription_manager_repos to empty list for the next time
  include_vars: default.yml
