---
# Default vars
# Do not change these variables
# Changes in this section are NOT supported

he_cmd_lang:
  LANGUAGE: en_US.UTF-8
  LANG: en_US.UTF-8
  LC_MESSAGES: en_US.UTF-8
  LC_ALL: en_US.UTF-8

he_vm_name: HostedEngine
he_data_center: Default
he_cluster: Default
he_local_vm_dir_path: /var/tmp
he_local_vm_dir_prefix: localvm
he_appliance_ova: ''
he_root_ssh_pubkey: ''
he_root_ssh_access: 'yes'
he_apply_openscap_profile: false
he_cdrom: ''
he_console_type: vnc
he_video_device: vga
he_graphic_device: vnc
he_emulated_machine: pc
he_minimal_mem_size_MB: 4096
he_minimal_disk_size_GB: 50
he_mgmt_network: ovirtmgmt
he_storage_domain_name: hosted_storage
he_ansible_host_name: localhost
he_ipv4_subnet_prefix: "192.168.222"
he_ipv6_subnet_prefix: fd00:1234:5678:900
he_webui_forward_port: 6900  # by default already open for VM console
he_reserved_memory_MB: 512
he_avail_memory_grace_MB: 200

he_host_ip: null
he_host_name: null
he_host_address: null
he_cloud_init_host_name: null
he_cloud_init_domain_name: null

he_smtp_port: 25
he_smtp_server: localhost
he_dest_email: root@localhost
he_source_email: root@localhost

he_force_ip4: false
he_force_ip6: false

he_pause_host: false
he_pause_after_failed_add_host: true
he_debug_mode: false

## Mandatory variables:

he_bridge_if: null
he_fqdn: null
he_mem_size_MB: max
he_vcpus: max
he_disk_size_GB: 61

he_enable_libgfapi: false
he_enable_hc_gluster_service: false
he_vm_mac_addr: null
he_remove_appliance_rpm: true
he_pki_renew_on_restore: false

## Storage domain vars:
he_domain_type: null  # can be: nfs | iscsi | glusterfs | fc
he_storage_domain_addr: null

## NFS vars:
## Defaults are null, user should specify if NFS is chosen
he_mount_options: ''
he_storage_domain_path: null
he_nfs_version: auto  # can be: auto, v4 or v3
he_storage_if: null

## ISCSI vars:
## Defaults are null, user should specify if ISCSI is chosen
he_iscsi_username: null
he_iscsi_password: null
he_iscsi_discover_username: null
he_iscsi_discover_password: null
he_iscsi_target: null
he_lun_id: null
he_iscsi_portal_port: null
he_iscsi_portal_addr: null
he_iscsi_tpgt: null
he_discard: false

# Define if using STATIC ip configuration
he_vm_ip_addr: null
he_vm_ip_prefix: null
he_dns_addr: null  # up to 3 DNS servers IPs can be added
he_vm_etc_hosts: false  # user can add lines to /etc/hosts on the engine VM
he_default_gateway: null
he_network_test: 'dns'  # can be: 'dns', 'ping', 'tcp' or 'none'
he_tcp_t_address: null
he_tcp_t_port: null

# ovirt-hosted-engine-setup variables
he_just_collect_network_interfaces: false
he_libvirt_authfile: '/etc/ovirt-hosted-engine/virsh_auth.conf'
he_offline_deployment: false
he_additional_package_list: []

# *** Do Not Use On Production Environment ***
# ********** Used for testing ONLY ***********
he_requirements_check_enabled: true
he_memory_requirements_check_enabled: true
