---
- name: Define Engine VM MAC address
  block:
  - name: Generate unicast MAC address
    shell: od -An -N6 -tx1 /dev/urandom | sed -e 's/^  *//' -e 's/  */:/g' -e 's/:$//' -e 's/^\(.\)[13579bdf]/\10/'
    changed_when: true
    register: mac_address
  - debug: var=mac_address
  - name: Set he_vm_mac_addr
    set_fact:
      he_vm_mac_addr: >-
        {{ mac_address.stdout if he_vm_mac_addr is not defined or he_vm_mac_addr is none else he_vm_mac_addr }}
  - name: Fail if MAC address structure is incorrect
    fail:
      msg: "Invalid unicast MAC address format. Got {{ he_vm_mac_addr }}"
    when: not he_vm_mac_addr | regex_search( "^[a-fA-F0-9][02468aAcCeE](:[a-fA-F0-9]{2}){5}$" )
- debug: var=he_vm_mac_addr
