- block:
    - name: Add Gluster storage domain
      ovirt_storage_domain:
          name: "{{ gluster_storage['dr_' + dr_target_host + '_name'] }}"
          critical_space_action_blocker: "{{ gluster_storage['dr_critical_space_action_blocker'] }}"
          domain_function: "{{ gluster_storage['dr_storage_domain_type'] }}"
          warning_low_space: "{{ gluster_storage['dr_warning_low_space'] }}"
          wipe_after_delete: "{{ gluster_storage['dr_wipe_after_delete'] }}"
          backup: "{{ gluster_storage['dr_backup'] }}"
          host: "{{ host_info.ovirt_hosts[0].name }}"
          data_center: "{{ gluster_storage['dr_' + dr_target_host + '_dc_name'] }}"
          auth: "{{ ovirt_auth }}"
          glusterfs:
              path: "{{ gluster_storage['dr_' + dr_target_host + '_path'] }}"
              address: "{{ gluster_storage['dr_' + dr_target_host + '_address'] }}"
      register: result

    - name: Log append to succeed_storage_domains
      set_fact:
        succeed_storage_domains: "{{ succeed_storage_domains }} + [ \"{{ gluster_storage['dr_' + dr_target_host + '_name'] }}\" ]"
      when: result is succeeded

    - name: Log append to failed_storage_domains
      set_fact:
        failed_storage_domains: "{{ failed_storage_domains }} + [ \"{{ gluster_storage['dr_' + dr_target_host + '_name'] }}\" ]"
      when: result is failed
  ignore_errors: "{{ dr_ignore_error_recover }}"
  tags:
      - fail_over
      - fail_back
