---
- name: Perform pre-install checks
  include_tasks: pre_install_checks.yml

- name: Install required packages for oVirt Engine deployment
  include_tasks: install_packages.yml
  when: not ovirt_engine_setup_perform_upgrade

- name: Run engine setup
  include_tasks: engine_setup.yml
