---
- name: Add external providers
  ovirt_external_provider:
    auth: "{{ ovirt_auth }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    type: "{{ item.type }}"
    url: "{{ item.url }}"
    password: "{{ item.password | default(omit) }}"
    tenant: "{{ item.tenant | default(omit) }}"
    auth_url: "{{ item.auth_url | default(omit) }}"
    data_center: "{{ item.data_center | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
    authentication_keys: "{{ item.authentication_keys | default(omit) }}"
  with_items:
    - "{{ external_providers | default([]) }}"
  tags:
    - external_providers
